### ISSUE TITLE
falco-driver-loader also as separate artifact

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco#1159]
**Motivation**

As we discussed several times it would be useful to distribute the `falco-driver-loader` separately, mainly to satisfy the following use cases:

- easy integration by other tools (ie. `falcoctl`) ( see also #1125 )
- one-liner installation (something like `wget URL/falco-driver/loader | bash && docker run .. falco` as proposed by @leodido during the yesterday's community call)

Currently, the script is just bundled within the [binary distribution](https://dl.bintray.com/falcosecurity/bin/x86_64/) (~40MB). 
The above use cases will benefit from a smaller download size by using a separate URL just for getting the script.

N.B.: this is an additional feature, the script will NOT be removed from the binary distribution.

**Feature**

Add another step to the release system to push the `falco-driver-loader` script separately in another (generic) bintray repo (eg. `https://dl.bintray.com/falcosecurity/script/` ?).

**Alternatives**

**Additional context**

**Comment by leodido** [comment]
After refactoring and revisiting the use cases for `falco-driver-loader` I think publishing it separately is not needed anymore probably, as told this morning to you @leogr 

I mean if someone wants to do I have nothing against it. It's just a very low priority thing since the use cases we have are already covered by the current build/release workflow.

**Comment by leogr** [comment]
And I agree as I told this morning :)

/close
