### ISSUE TITLE
DRIVER_VERSION for the master docker image

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/falco#1178]
**Describe the bug**

When we merge a change to the Falco master branch that updates the driver version we are in a situation that until the test-infra yaml files are updated we don't provide pre-built kernel modules. This can create a problem to all those who want to try the latest features or checkout if Falco works after some bugfixes.

To avoid this we can take two roads:

- Always set `dev` to `DRIVER_VERSION` in the falco-driver-loader script until we are in a released tag
OR
- Make sure we have some mechanisms in place so that yaml files go to test-infra whenever we merge a change to the driver verison

My vote goes to the second option, also because with option 1 is very easy to forget the test-infra update and release a Falco version without the prebuilt drivers.

**How to reproduce it**

See https://github.com/falcosecurity/falco/issues/1078#issuecomment-622580309 for reference.

**Expected behaviour**

falco-driver-loader finds the prebuilt driver for supported kernels.

**Comment by leodido** [comment]
Honestly, I don't think this can be classified as a bug.

In the log reported at comment https://github.com/falcosecurity/falco/issues/1078#issuecomment-622580309 infact the `falco-driver-loader` first of all tries to build the driver locally ([here](https://github.com/falcosecurity/falco/blob/master/scripts/falco-driver-loader#L184)).

Since it is not able to build it locally, it outputs `Running dkms build failed, couldn't find /var/lib/dkms/falco/47374b2b73734d509f3c99890c80be5242021c3d/build/make.log` ([here](https://github.com/falcosecurity/falco/blob/master/scripts/falco-driver-loader#L197)) and finally it fallbacks to look for a prebuilt one.

Classifying this a bug means that we commit to provide all the possible prebuilt drivers, which is not the path we want to follow IMHO :)

**Comment by fntlnz** [comment]
Please feel free to find a better label.
I wasn't able to recognize one.

**Comment by ianhundere** [comment]
same issue here, but this was after updating to EKS 1.16 from EKS 1.15.

we were using 0.19.0 before this without issue.

using the latest falcosecurity/falco:master image did not resolve the issue.

Your kernel headers for kernel 4.14.173-137.229.amzn2.x86_64 cannot be found at
/lib/modules/4.14.173-137.229.amzn2.x86_64/build or /lib/modules/4.14.173-137.229.amzn2.x86_64/source.
* Running dkms build failed, couldn't find /var/lib/dkms/falco/a259b4bf49c3330d9ad6c3eed9eb1a31954259a6/build/make.log
* Trying to load a system falco-probe, if present
* Trying to find precompiled falco-probe for 4.14.173-137.229.amzn2.x86_64
Found kernel config at /host/boot/config-4.14.173-137.229.amzn2.x86_64
* Trying to download precompiled module from https://s3.amazonaws.com/download.draios.com/stable/sysdig-probe-binaries/falco-probe-a259b4bf49c3330d9ad6c3eed9eb1a31954259a6-x86_64-4.14.173-137.229.amzn2.x86_64-f0c8ced41ae4d0e71aa715068964ce9f.ko
curl: (22) The requested URL returned error: 404 Not Found
Download failed, consider compiling your own falco-probe and loading it or getting in touch with the Falco community
Tue May  5 14:08:36 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Tue May  5 14:08:36 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Tue May  5 14:08:37 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
Tue May  5 14:08:38 2020: Unable to load the driver. Exiting.
Tue May  5 14:08:38 2020: Runtime error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco-probe module is loaded.. Exiting.
