### ISSUE TITLE
Falco unix socket permissions

### ISSUE THREAD

**Issue by nibalizer** [falcosecurity/falco#1351]
**Describe the bug**

When falco creates it's unix socket, it creates it as `/var/run/falco.sock` as a unix domain socket with permissions `700` and `root/root`. While this is great for security, it means that any consuming utility like the falco-exporter or a [toy python program](https://github.com/nibalizer/miscelaneous/blob/master/logdna/falco-logdna.py) would need to run as root to access the socket.

**How to reproduce it**

1. Start Falco
2. Run a program (e.g. client-go examples) as nonroot

**Expected behaviour**

There should be a way to run client utilities without running them as root.

**Screenshots**

**Environment**

- Falco version: 0.24.0

- System info:

{
  "machine": "x86_64",
  "nodename": "nibz-falco-dev",
  "release": "4.15.0-42-generic",
  "sysname": "Linux",
  "version": "#45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018"
}
- Cloud provider or hardware configuration:
- OS: Linux

- Kernel:  4.15.0-42-generic #45-Ubuntu

- Installation method: DEB

**Additional context**

Briefly discussed on  the 8/12/2020 call.

One option would be to have a `falco` group installed by the deb/rpm package. The socket could be `770 root:falco` and utilities that need access could run as a user in the `falco` group.

**Comment by kris-nova** [comment]
I think it might be useful to have read-only access for non-root users

or at least the ability to enable this functionality

**Comment by PhilipSchmid** [comment]
What do you think about implementing the permissions `740 root:falco` for the Falco socket and automatically creating a `falco` group when installing it? This way it would be possible to also create the `falco` group with the same GID inside the falco-exporter container. This would allow that the falco-exporter process could be run with a service user (UID != 0) but since this service user could be added to the `falco` group, it would have read access to the Falco socket anyway.

Regards,
Philip

**Comment by leogr** [comment]
/reopen

See 
- https://kubernetes.slack.com/archives/CMWH3EH32/p1624974980314300
- https://kubernetes.slack.com/archives/CMWH3EH32/p1624975531316700
