### ISSUE TITLE
Falco.json file isn't populated

### ISSUE THREAD

**Issue by JScrivanich** [falcosecurity/falco#1352]
We install Falco when we bake new AMIs. So when a new instance is spun up with our ami, falco is already installed and starts on its own.  

This week when we released new patched AMIs, I noticed issues with the new falco version 0.24.0. The issues are outlined below.  I rolled back to our AMIs using falco version 0.23.0 where we don't experience this issue

When we use `/etc/yum.repos.d/falcosecurity.repo https://falco.org/repo/falcosecurity-rpm.repo` to install Falco, I noticed that in /var/log falco.json file is present but doesn't populate (it is an empty file).  When I run `service falco status`, it shows falco is running.  If I run `service falco start` then the falco.json file starts populating immediately and we begin to get alerts.

When we use `/etc/yum.repos.d/falcosecurity.repo https://falco.org/repo/falcosecurity-rpm-dev.repo` to install Falco, I noticed that in /var/log falco.json isn't even in the directory. When I run `service falco status`, it shows falco is running.  If I run `service falco start` then the falco.json file appears and begins to populate.

This issue is presenting on our Amazon Linux 2 Instances

**Comment by leodido** [comment]
Hey @JScrivanich, `https://falco.org/repo/falcosecurity-rpm.repo` is the repo file for stable Falco releases (like Falco 0.23.0, Falco 0.24.0, etc.).

Instead, `https://falco.org/repo/falcosecurity-rpm-dev.repo` is the repo file for development Falco releases that automatically get created every time a patch is merged into the master branch of this repository.

So help me understand.

Is this issue about missing `/var/log/falco.json` happening only for Falco 0.24.0?
Or it is happening for the development releases of Falco (eg., Falco [0.24.0-41+1f1f7c1](https://bintray.com/falcosecurity/rpm-dev/falco/0.24.0-41%2B1f1f7c1))?

Thanks :)

**Comment by JScrivanich** [comment]
Hey @leodido The issue is present in both.  We normally use the stable Falco release.  When I discovered this issue using the stable Falco release, I decided to then try the repo file for development just to see if the issue was persisting there as well and it was.  But the issue persists in both

**Comment by fntlnz** [comment]
We had a discussion on the Slack channel with @JScrivanich and it looks like they were thinking that Falco by default writes the events to that file.
It turns out that it is not correct.

By default you can inspect Falco logs doing `systemctl status falco` or `journalctl -xef -u falco`

To have something like what was requested here one needs to open the falco configuration file `/etc/falco/falco.yaml` and set `file_output.enabled` to true.

`json_output: false` can also be set to true to have a json file.

I'm closing this since it's just a question that has been answered and it's not a bug.
However, feel free to continue the discussion here if you have any more doubts @JScrivanich - you're very welcome!

/kind feature
/triage support

/close
