### ISSUE TITLE
The falco has a huge overhead when the host has a large syscalls

### ISSUE THREAD

**Issue by wcc526** [falcosecurity/falco#1404]
just run `dd if=/dev/zero of=/dev/null bs=500 count=100M`

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 36849 root      20   0  192976  25720   5484 S  24.3  0.3   0:50.34 falco

The falco cpu is up to 24%!

And the disk write is hang
with falco
[root@test-falco-15dccb4ab ~]# dd if=/dev/zero of=/dev/null bs=500 count=100M
104857600+0 records in
104857600+0 records out
52428800000 bytes (52 GB) copied, 261.711 s, 200 MB/s

without falco
[root@test-falco-15dccb4ab ~]# dd if=/dev/zero of=/dev/null bs=500 count=100M
104857600+0 records in
104857600+0 records out
52428800000 bytes (52 GB) copied, 116.816 s, 449 MB/s

The disk write slower 100% ! 116s -> 261s

**Comment by mstemm** [comment]
One of the things we discussed during the community call is the ability to skip certain events in the kernel by event type. The sysdig code itself supports this, I believe: scap_unset_eventmask https://github.com/draios/sysdig/blob/dev/userspace/libscap/scap.c#L2081. If I remember, this pushes the event type all the way down to the kernel and drops the event there.

So that would be as efficient as you could make it.

**Comment by fntlnz** [comment]
Notes from the community call:

- For the disk write slowed down: @ldegio  was suggesting that we can try to profile what happens in this scenario. However this looks like more an issue in the engine since not a lot of rules are hit in a situation like that. The CPU usage is related to the amount of events, this is a known limitation. We can probably improve the situation by doing filtering in the driver. Tl;dr: 24% percent is probably something to take into account if you want to run falco in a machine with that usage pattern.
- First experiment we can do is to put an `UF_ALWAYS_DROP` in https://github.com/draios/sysdig/blob/dev/driver/syscall_table.c#L59 to see how it behaves.
