### ISSUE TITLE
feat: a better and thread-safe logger

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco#1476]
**Motivation**

Currently, Falco comes with a custom logger implementation: the `falco_logger` class. Moreover, it is not thread-safe.
I'd love to have a thread-safe logger, so we don't have to worry about using it everywhere needed. That could be very helpful in some new upcoming features using threads, like, for example, https://github.com/falcosecurity/falco/pull/1451.

**Feature**

Replace the current logger by using a third-party library that already implements a simple but thread-safe logger. 

**Alternatives**

We could improve the current one. But it would be like re-implement the wheel. Also, it's not worth maintaining a custom one, IMHO.

**Additional context**

After a quick chat with @leodido, we agreed that the current logger should be replaced.

I haven't searched for a replacement yet. Any proposal is welcome.

**Comment by leodido** [comment]
I've been able to found some notes about a preliminary study of this topic!

Among various candidates, it seems that my notes vote for [spdlog](https://github.com/gabime/spdlog) for the following reasons:

- very [fast](https://github.com/gabime/spdlog#benchmarks)
- multi-threaded loggers
- rich formatting
- header-only C++11 library
- async (optional) mode
- various targets (rotating, console with colors yay, syslog, etc.)
- log filtering/levels at runtime also
- it can store logs in a - guess what - ring buffer to later show them

Also, my notes highlight the main issue of this refactoring is in the underlying libraries (libsinsp, libscap) Falco uses.
Because they use another logger.

So I see two tasks here:
- [ ] make the underlying optionally libraries use this logger
- [ ] make Falco use this logger for its logs and make it configure the underlying libraries to use it too

If you want we can spot 1-2 days to work on this together.

**Comment by leogr** [comment]
I'm in! :partying_face:

**Comment by leodido** [comment]
Before proceeding with the implementation, I and @leogr wrote and run some benchmarks this morning to quantify eventual improvements in the performances.

Here the results.

<details><summary>Log to stderr only, 50K messages, 3 runs</summary>

spdlog: 5381/sec
falco_logger: 5982/sec

</details>

<details><summary>Log to syslog only, 50K messages, 3 runs</summary>

spdlog: 64663/sec
falco_logger: 69297/sec

</details>

<details><summary>Log to syslog only (multi-threading), 10 threads, 1M messages, 3 runs</summary>

spdlog: 61935/sec
falco_logger: 60980/sec

<details>

Since:
- we do not notice any real boost in the performances (at least in our use case)
- the `spdlog` library doesn't give us a way to customize the log levels (as far as we know)

We decided to put this task on hold.

Before the 1.0 of Falco we'll re-evaluate whether this task is worth or not, just because the `spdlog` interfaces are very nice.
