### ISSUE TITLE
Since the Falco dirver rename, Falco is unable to unload the falco_probe module

### ISSUE THREAD

**Issue by JPLachance** [falcosecurity/falco#1486]
**Describe the bug**

In Falco 0.23.0, the Falco driver was renamed from `falco_probe` to `falco`.

https://github.com/falcosecurity/falco/commit/3ec4b5b65272e8c86504edd29cf36023880aec43

That change changed the value of `DRIVER_NAME` which affected the falco-driver-loader script ability to run `rmmod falco_probe`.

Basically:

- The falco-driver-loader script does `rmmod falco 2>/dev/null`
- The `lsmod | cut -d' ' -f1 | grep -qx falco` test returns true because `falco_probe` is still loaded
- The script tries over and over for a minute
- The script ends with the `"* falco module seems to still be loaded, hoping the best"` message

<img width="814" alt="Screen Shot 2020-11-13 at 1 02 43 PM" src="https://user-images.githubusercontent.com/3448802/99106879-f634e480-25b2-11eb-9bd1-3babafcfa6b9.png">

**How to reproduce it**

- Deploy Falco 0.22.0 on a host
- Validate the `falco_probe` module is loaded with `lsmod | grep falco`
- Upgrade to Falco 0.26.2
- Watch it try to `rmmod falco`

**Expected behaviour**

The https://github.com/falcosecurity/falco/blob/master/scripts/falco-driver-loader script should look for the old version of the Falco module and run `rmmod`.

For example:
```bash
if lsmod | cut -d' ' -f1 | grep -qx "falco_probe"; then
  echo "* Module falco_probe still present"

  if rmmod -v "falco_probe" 2>/dev/null; then
    echo "* Unloading falco_probe module succeeded"
  fi
fi
```

**Comment by leodido** [comment]
I confirm this issue exists.

I see two paths to fix it, let's discuss them together!

1. make the `DRIVER_NAME` variable configurable from the environment - ie., by wrapping its [declaration](https://github.com/falcosecurity/falco/blob/648bb6294fa7615ad19bcea1647e264b607e11bb/scripts/falco-driver-loader#L489) with something like `[[ -z "${DRIVER_NAME}" ]] && DRIVER_NAME=@PROBE_NAME@`

2. check the Falco version and if its >= 0.23 look for a kernel module named `falco` otherwise look for a kernel module named `falco_probe`

I like solution 1 because gives us more flexibility. But, as said, I'm interested in hearing what y'all think!

/assign

**Comment by leogr** [comment]
> 1. make the `DRIVER_NAME` variable configurable from the environment - ie., by wrapping its [declaration](https://github.com/falcosecurity/falco/blob/648bb6294fa7615ad19bcea1647e264b607e11bb/scripts/falco-driver-loader#L489) with something like `[[ -z "${DRIVER_NAME}" ]] && DRIVER_NAME=@PROBE_NAME@`
> 2. look also for a kernel module named `falco_probe` (old name)

Unfortunately, I believe the first option is not enough, see my [comment here](https://github.com/falcosecurity/falco/pull/1488#issuecomment-728138234). WDYT?

**Comment by leodido** [comment]
The solutions I proposed (especially the first one) were only regarding what the user reported

> The https://github.com/falcosecurity/falco/blob/master/scripts/falco-driver-loader script should look for the old version of the Falco module and run rmmod.

Just to clarify: the need of removing the old kernel-module from/with `dkms` is a valid point I agree with, but it's a second step that was not mentioned by @JPLachance.

As written [here](https://github.com/falcosecurity/falco/pull/1488#issuecomment-728805281), I think we should also add a third command to the `falco-driver-loader` script to cover the scenario in which an user may want to delete a old/different kernel-module (eg., `falco_probe`) and **then** insert a new one (calling again the script) with a different name (eg., `falco`).

**Comment by JPLachance** [comment]
@leodido, i see your point, but I feel like your solution won't be super convenient to all Falco users.

We want to deploy Falco, tweak it a little bit, build automations around it. When the time comes to upgrade Falco, we should not be forced to think about "ho I need to remove that old kernel module before upgrading".

Upgrades are not friction-less at the moment and we should do as much as possible to make them friction-less. By incorporating in the falco-driver-loader script the logic to automatically cleanup old versions, the user won't have to think about it, won't report a bug ans will be happier 😄 

In the end, it's your decision, you are the maintainers.

**Comment by leodido** [comment]
@JPLachance thanks for your opinion, it means a lot to us to have feedback from our users :)

I totally agree that the upgrade process between different Falco version should be straightforward.

Anyways, here we are talking about a very specific thing that happened: the rename of the Falco kernel-module driver (from `falco_probe` to `falco`).

It's for this reason that the update from Falco versions <= 0.23 (when that change was made) to the recent Falco version presents a problem in removing the old kernel module, as you described.

This exact behavior could also affect our official packages. So, I tend to prefer a solution that does not involve only `falco-driver-loader` script.

Since it's very unlikely that we'll change again the name of the kernel module I was just trying to separate and prioritize the steps we need to make the upgrade process (even in such cases) frictionless.

But, we have the same goal in the end! :)
