### ISSUE TITLE
Syscall event drops on OpenShift platform

### ISSUE THREAD

**Issue by christiaanvaken** [falcosecurity/falco#1573]
We have implemented Falco on OpenShift by using the Helm charts. Recently we have noticed a lot of syscall event drops, somethings the value of n_drops is over 100000. We have changed the resources section of the configuration to change rhe requests for cpu to 500m and the limits for the cpu to 1000m. The dropped events reduced a lot but we are still getting a lot of drops sometimes. 

Is there any advice or solutions how to fix this on OpenShift?

**Comment by christiaanvaken** [comment]
> @christiaanvaken: The label(s) `kind/"help, kind/wanted"` cannot be applied, because the repository doesn't have them.



> @christiaanvaken: There is not a label identifying the kind of this issue.
> Please specify it either using `/kind <group>` or manually from the side menu.

How do I do that?

**Comment by leogr** [comment]
Hi,

when opening an issue, there's a template that should be filled. Providing those details helps us to understand the issue.  The template also includes instructions to set the correct labels. Please, do not remove it. 

/kind bug

Anyway, in https://github.com/falcosecurity/falco/issues/1403 is present a handy checklist to debug kind of issues.
It could help in identifying the root cause of the syscall drops you are noticing.
