### ISSUE TITLE
Unable to detect events with containerd and kubernetes

### ISSUE THREAD

**Issue by rayanebel** [falcosecurity/falco#1630]
**Describe the bug**

Hi everyone,

I'm not sure if it's a bug or a misunderstanding from my side. I have a kubeadm cluster installed and i switch from docker to containerd because of the deprecation of docker.

I've installed falco directly on the worker node _(not as a deamonset)_ as the documentation recommend. I've update the systemd unit file to add the reference needed when we use containerd. Everything is up and running but now, when I try to create a pod and try to exec a shell on it I have no entry in the log which tell me that someone has spanwed a shell in pod xxxx.

Do I miss something ? I do not find in the documentation a lot of documentation about how to use falco with containerd.

Here you can find my systemd unit file.

```
[Unit]
Description=Falco: Container Native Runtime Security
Documentation=https://falco.org/docs/
[Service]
Environment="FALCO_ARGS=--cri=/run/containerd/containerd.sock --disable-cri-async -pk"
Type=simple
User=root
ExecStartPre=/sbin/modprobe falco
ExecStart=/usr/bin/falco --pidfile=/var/run/falco.pid $FALCO_ARGS
ExecStopPost=/sbin/rmmod falco
UMask=0077
TimeoutSec=30
RestartSec=15s
Restart=on-failure
PrivateTmp=true
NoNewPrivileges=yes
ProtectHome=read-only
ProtectSystem=full
ProtectKernelTunables=true
RestrictRealtime=true
RestrictAddressFamilies=~AF_PACKET
[Install]
WantedBy=multi-user.target
```

When I try to do another action for example I open a shell on a pod and I try to create a file in `/etc` I found some entries in the logs but some data are missing

```bash
Apr 23 11:37:35 cks-worker falco[8815]: 11:37:35.770964137: Error File below /etc opened for writing (user=root user_loginuid=-1 command=touch /etc/bbb parent=bash pcmdline=bash file=/etc/bbb program=touch gparent=<NA> ggparent=<NA> gggparent=<NA
> container_id=host image=<NA>)
Apr 23 11:37:35 cks-worker falco[8815]: 11:37:35.770964137: Error File below /etc opened for writing (user=root user_loginuid=-1 command=touch /etc/bbb parent=bash pcmdline=bash file=/etc/bbb program=touch gparent=<NA> ggparent=<NA> gggparent=<NA
> container_id=host image=<NA>)
```

**Additional info**: I'm using the default rules file.

**How to reproduce it**

- Install falco in the worker node
- Update the systemd unit file to include configuration related to containerd
- Create a pod

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: falco-test
  namespace: default
spec:
  containers:
  - image: nginx
    name: falco-ltest
```
- exec a shell on the pod
```bash
kubectl exec -it falco-test -- bash
```
- check the falco logs `journalctl -fu falco` _(No events when a shell has been spawned)_
- Inside the pod create a file in `/etc` and check the logs again _(Events with incomplete data)_

**Expected behaviour**

- We should have a event when we open a shell in the pod. It's working when we are using docker as container runtime.
- We should have events with all the metadata _(pod_name...)_.

**Environment**

- Falco version:

```
Falco version: 0.28.0
Driver version: 5c0b863ddade7a45568c0ac97d037422c9efb750
```

- System info:
- Cloud provider : GCP
- OS:
```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel:
`Linux cks-master 5.4.0-1042-gcp #45~18.04.1-Ubuntu SMP Tue Apr 13 18:51:16 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

- Installation method:
DEB

**Comment by rayanebel** [comment]
Hi @leogr 

Thanks for your reply.

I have stop the falco systemd service and run falco manually with the command that you provide me. When, I create a pod and exec a shell on it I have an log in stdout but, some metadata are missing _(e.g namespace)_


```
sudo /usr/bin/falco --cri /run/containerd/containerd.sock -pk

Tue May 11 16:36:25 2021: Falco version 0.28.0 (driver version 5c0b863ddade7a45568c0ac97d037422c9efb750)
Tue May 11 16:36:25 2021: Falco initialized with configuration file /etc/falco/falco.yaml
Tue May 11 16:36:25 2021: Loading rules from file /etc/falco/falco_rules.yaml:
Tue May 11 16:36:25 2021: Loading rules from file /etc/falco/falco_rules.local.yaml:
Tue May 11 16:36:26 2021: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Tue May 11 16:36:26 2021: Starting internal webserver, listening on port 8765

16:39:38.752534563: Notice A shell was spawned in a container with an attached terminal (user=root user_loginuid=-1
 k8s.ns=<NA> k8s.pod=<NA> container=e22578a37c49 shell=bash parent=runc cmdline=bash terminal=34816 container_id=e2
2578a37c49 image=docker.io/library/nginx) k8s.ns=<NA> k8s.pod=<NA> container=e22578a37c49 k8s.ns=<NA> k8s.pod=<NA> 
container=e22578a37c49

16:39:57.071900639: Error File below /etc opened for writing (user=root user_loginuid=-1 command=touch /etc/toto pa
rent=bash pcmdline=bash file=/etc/toto program=touch gparent=<NA> ggparent=<NA> gggparent=<NA> container_id=e22578a
37c49 image=docker.io/library/nginx) k8s.ns=<NA> k8s.pod=<NA> container=e22578a37c49 k8s.ns=<NA> k8s.pod=<NA> conta
iner=e22578a37c49 k8s.ns=<NA> k8s.pod=<NA> container=e22578a37c49
```

So what the difference with the systemd service ? I think I have provided all the flag related to containerd ?

**Comment by rayanebel** [comment]
Hi @leodido 
I carried out the same steps below and re-execute the `falco` command manually on a fresh cluster (GCE+kubeadm) but, I have again the same bug. I'm not able to see any events. I don't understand why it was working when we talked last time. I've just installed containerd with default configuration and install falco. 

```
root@cks-worker:/etc/containerd# sudo /usr/bin/falco --cri /run/containerd/containerd.sock -pk
Mon Jun 14 08:47:23 2021: Falco version 0.28.1 (driver version 5c0b863ddade7a45568c0ac97d037422c9efb750)
Mon Jun 14 08:47:23 2021: Falco initialized with configuration file /etc/falco/falco.yaml
Mon Jun 14 08:47:23 2021: Loading rules from file /etc/falco/falco_rules.yaml:
Mon Jun 14 08:47:24 2021: Loading rules from file /etc/falco/falco_rules.local.yaml:
Mon Jun 14 08:47:24 2021: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Mon Jun 14 08:47:24 2021: Starting internal webserver, listening on port 8765

08:48:25.591044983: Warning Shell history had been deleted or renamed (user=root user_loginuid=-1 type=openat command=bash fd.name=/root/.bash_history name=/root/.bash_history path=<NA> oldpath=<NA> k8s.ns=<NA> k8s.pod=<NA> container=host) k8s.ns
=<NA> k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host
08:49:19.167578644: Error File below /etc opened for writing (user=root user_loginuid=-1 command=touch toto parent=bash pcmdline=bash file=/etc/toto program=touch gparent=<NA> ggparent=<NA> gggparent=<NA> container_id=host image=<NA>) k8s.ns=<NA>
 k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host
```

**Comment by rayanebel** [comment]
@leodido Now, just for debugging purpose, I tried to install falco by using `helm` and I get the same results. falco fallback to container=host when I'm trying to generate events.

```
09:37:04.037899240: Error File below /etc opened for writing (user=root user_loginuid=-1 command=touch test2 parent=bash pcmdline=bash file=/etc/test2 program=touch gparent=<NA> ggparent=<NA> gggparent=<NA> container_id=host image=<
NA>) k8s.ns=<NA> k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host
09:38:53.075060899: Error File below /etc opened for writing (user=root user_loginuid=-1 command=touch /etc/test parent=bash pcmdline=bash file=/etc/test program=touch gparent=<NA> ggparent=<NA> gggparent=<NA> container_id=host image=<NA>) k8s.ns
=<NA> k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host
```

`helm install falco falcosecurity/falco --set ebpf.enabled=true -n falco`

Something went wrong with containerd but I don't understand why ? Do you have other steps to do to troubleshoot this problem ?

**Comment by leogr** [comment]
> `helm install falco falcosecurity/falco --set ebpf.enabled=true -n falco`
> 
> Something went wrong with containerd but I don't understand why ? Do you have other steps to do to troubleshoot this problem ?

Quick one:
- Is the containerd unix socket located in `/run/containerd/containerd.sock` on your system ?

> @leogr If you need I can give you an access to the cluster or the VM _(it's a sandbox)_ if it's better for you.

Please contact me via DM on slack.

**Comment by antonioribezzi** [comment]
Hi, we're encountering the same issue.
We're running Anthos 1.8 on VMware, and we switched to Containerd. 
Since we switched to Containerd, Falco is not able to detect privileged containers anymore:

{"output":"09:51:04.431861217: Notice OIZ DEBUG Privileged container started (user=root user_loginuid=-1 command=dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2376 --tlsverify --tlscacert /certs/server/ca.pem --tlscert /certs/server/cert.pem --tlskey /certs/server/key.pem k8s.ns=default k8s.pod=dind container=6b068625c0e4 image=nexus.intra.stzh.ch:18080/x86_64/stzh/docker/docker:19.03.12-dind-1 container.Privileged=false)","priority":"Notice","rule":"OIZ DEBUG Launch Privileged Container","time":"2021-07-23T09:51:04.431861217Z", "output_fields": {"container.id":"6b068625c0e4","container.image.repository":"nexus.intra.stzh.ch:18080/x86_64/stzh/docker/docker","container.image.tag":"19.03.12-dind-1","container.privileged":false,"evt.time":1627033864431861217,"k8s.ns.name":"default","k8s.pod.name":"dind","proc.cmdline":"dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2376 --tlsverify --tlscacert /certs/server/ca.pem --tlscert /certs/server/cert.pem --tlskey /certs/server/key.pem","user.loginuid":-1,"user.name":"root"}}

We're using Calico as CNI, and Falco runs like that:
/usr/bin/falco --cri /run/containerd/containerd.sock -K /var/run/secrets/kubernetes.io/serviceaccount/token -k https://100.126.1.1 -pk

**Comment by holyspectral** [comment]
I noticed this issue too when `containerd` or `crio` is used.  It looks like the logic in [falco-libs](https://github.com/falcosecurity/libs/blob/master/userspace/libsinsp/cri.cpp#L305) doesn't support the recent `containerd` and `crio` .    I'm going to work on a fix.

**Comment by wuestkamp** [comment]
I'm seeing the same issue like @rayanebel where all metadata is missing.
Tested with containerd (1.3.3|1.5.2) and Falco (0.21.0|0.28.0|0.29.1).

`program=sed gparent=<NA> ggparent=<NA> gggparent=<NA> container_id=host image=<NA>) k8s.ns=<NA> k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host k8s.ns=<NA> k8s.pod=<NA> container=host`

@holyspectral was your PR about this issue or just about Falco not detecting privileged containers?

Anyone knows if there is a workaround for Falco+Containerd to show container metadata?

**Comment by leogr** [comment]
AFAIK, this issue should be fixed in libs by https://github.com/falcosecurity/libs/pull/79, but the version of the lib has been not yet upgraded in Falco, so keep it open.

**Comment by holyspectral** [comment]
It looks like there are multiple issues in this case, so I tried to summarize them as below.  Hope this will help other people troubleshoot missing metadata issue in their falco events. 

1. `container_id=host`.  Other than missing metadata, if you also see `container_id=host` even when you trigger the event from a container, you probably hit this issue. This could be caused by non-default cgroup path.  Falco parses a process' cgroup path in order to retrieve its container ID and then use the ID to query container runtime like docker, containerd and kubernetes.   There are some discussion and potential fix in this issue about this cgroup path problem.  https://github.com/falcosecurity/falco/issues/1568
When you see this, the result of `cat /proc/self/cgroup` from a container will help people to troubleshoot further.

2. Missing `container.image.*` If you see a valid container ID (like `container_id=8ae22495737c`), but have no metadata about its container image, you may need to check if you have the right socket path setup.  You can check and specify the correct path in helm charts overrides or falco command line.  For example:
```
containerd:
  enabled: true
  socket: /xxxx/containerd.sock
```
Providing grpcurl result from falco container will also be very helpful.  You can find the step here: https://github.com/falcosecurity/falco/issues/1568#issuecomment-796897481

3. kubernetes API server connection problem.  If you can see a valid container ID but not those with `k8s` prefix, you may want to check if falco is allowed to connect to your kubernetes API server.  
4. If you can see all metadata and just have problem to trigger a rule with `container.privileged` condition after containerd/crio is used, this was fixed in  https://github.com/falcosecurity/libs/pull/79

**Comment by wuestkamp** [comment]
Thanks for the list @holyspectral !
For me it was number 1.
After setting `SystemdCgroup = true` in `/etc/containerd/config.toml`, like explained in https://github.com/falcosecurity/falco/issues/1568, and after restarting containerd and containers, Falco is getting the correct container_id and metadata

**Comment by leogr** [comment]
Thank you, for the detailed report @holyspectral 
Very appreciated :+1:
