### ISSUE TITLE
Excluding Namespaces from Detection

### ISSUE THREAD

**Issue by jonathang-simplex** [falcosecurity/falco#1779]
I'm interested in applying the falco solution in a gradual way to a single namespace at a time.

Please provide documentation on:
1) How to exclude entire namespaces (in the k8s cluster) from detection by falco.
2) How to apply falco security only to a specific list of namespaces in the k8s cluster.

Thanks

**Comment by kiper-prog** [comment]
Hi! 
Have you found a solution?

**Comment by yuliyantsvetkov** [comment]
This is not serious, folks. Automatic closure of issues that are not answered does not bring the trust we would like to see from this product, and refrain new contributors from joining the project.

**Comment by michal0000000** [comment]
Bump. Seems like a feature important enough to reconsider the usability of this project. 

EDIT: If my understanding is correct, syscalls are monitored on the host so dropping events based on namespaces is troublesome (it requires dropping them *after* an events has been triggered and *after* it has been enriched with necessary metadata. To achieve this one would have to play around with the [node selection](https://github.com/falcosecurity/charts/blob/master/charts/falco/values.yaml#L100) capabilities in addition with further [rule matching](https://github.com/falcosecurity/charts/blob/master/charts/falco/values.yaml#L760). Tbh, I would still prefer if it was easier to set up due to how common such a use case is.

**Comment by fr4nsyz** [comment]
I second @michal0000000 's response. I have a similar use case for this as well and would really appreciate such a feature.
