### ISSUE TITLE
`http_output` always uses "Content-Type: application/json" even if json formatting is disabled

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco#1824]
**Describe the bug**

`Content-Type: application/json` is always sent :point_down: 

https://github.com/falcosecurity/falco/blob/f035829ca2881b70a4d13e22abb5f8eb828d3a5f/userspace/falco/outputs_http.cpp#L31

regardless of the value of json formatting option :point_down: 

https://github.com/falcosecurity/falco/blob/f035829ca2881b70a4d13e22abb5f8eb828d3a5f/falco.yaml#L68

**How to reproduce it**

**Expected behaviour**

Perhaps, `text/plain` when `json_output: false` ?

**Screenshots**

**Environment**

- Falco version:

- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

**Comment by FedeDP** [comment]
Looking at the code, it seems like `text/plain` is a good choice:
`falco_formats::format_event()` formats the event to a string line with:
`formatter->tostring_withformat(evt, line, gen_event_formatter::OF_NORMAL);`
as the output line is also sent as event json "output" field in case json output is enabled.
Otherwise, we just send the output string.

**Comment by FedeDP** [comment]
A super simple PR has been created.
