### ISSUE TITLE
Adjusted falco to stop collecting certain types of syscalls

### ISSUE THREAD

**Issue by kooriboh** [falcosecurity/falco#2015]
Hi there,

To improve performance based on my needs, I'm trying to adjust the driver so that falco driver only collects **execve** logs from the system. I only found documentation that support [monitoring new syscalls with Falco](https://falco.org/blog/falco-monitoring-new-syscalls/), but no documentation about removing those syscalls.
I wonder how I can remove other syscalls from driver so falco agent only collects **execve** logs. Hope someone can help.

Thanks,
Huy

**Comment by Andreagit97** [comment]
Hi @kooriboh this is a good point. Right now Falco cannot collect only one syscall. We tried to reduce the number of captured syscalls with the `simple_consumer` mode, enabled by default since Falco `0.31.0`. The next step will be to allow users to collect only specific syscalls like in your case. We had a discussion about that here https://github.com/falcosecurity/libs/issues/267. Here the focus is the eBPF probe, but the same idea can be applied to the kernel module. We will update you when will have news about it :)

**Comment by FedeDP** [comment]
Hi!
I just wanted to share that PR https://github.com/falcosecurity/libs/pull/521 aims at allowing that, at least in a programmatic way.
There is currently no play to support any config in Falco to switch off syscalls/tracepoints because it is way too easy to completely break Falco doing that (eg: causing memleaks and other sort of issues).
At least, it will be much easier to patch Falco to switch off some syscalls :)

**Comment by incertum** [comment]
@kooriboh this feature will be available in Falco 0.35, see for example this comment in https://github.com/falcosecurity/falco/issues/2433#issuecomment-1447620920

**Comment by FedeDP** [comment]
/close

This will be fixed by 0.35.0.
