### ISSUE TITLE
Falco kernel module fails to compile in Fedora

### ISSUE THREAD

**Issue by q2dg** [falcosecurity/falco#2481]
**Describe the bug**

In Fedora 37 I've done these steps to install Falco by using its kernel module...

```
rpm --import https://falco.org/repo/falcosecurity-packages.asc
curl -s -o /etc/yum.repos.d/falcosecurity.repo https://falco.org/repo/falcosecurity-rpm.repo
dnf upgrade && reboot	
dnf install dialog kernel-devel-$(uname -r) 
dnf install falco   #### (I've answered "Kmod" and "No")
``` 

...but I've got this error

![errorFalco](https://user-images.githubusercontent.com/7274874/230715105-1b1d8f54-951d-4533-986c-db64963affd2.png)

As you can see, Falco's version tried to be installed is 0.34.1 and system's kernel's version is 6.2.8

**Expected behaviour**

Same steps done in Ubuntu 22.04 ends successfully
Thanks!

**Comment by Andreagit97** [comment]
Ei @q2dg this is due to the fact that Fedora 37 uses a very recent kernel version `6.2.8` while ubuntu 22.04 will probably use an older kernel version. BTW this issue is already solved here https://github.com/falcosecurity/libs/issues/918. Falco 0.35 will be shipped with this fix :) (Falco 0.35 will be released at the end of May)

**Comment by q2dg** [comment]
Ah, ok! 
Thanks a lot for your kind explanation (and sorry for the inconvenience)
I'll close this issue, then
Thanks!

**Comment by Andreagit97** [comment]
No inconvenience at all! You're welcome!
