### ISSUE TITLE
add new syscalls collecting support

### ISSUE THREAD

**Issue by MagpieRYL** [falcosecurity/falco#2543]
**Motivation**

Some intrusion method:
 - inserting kernel module for persistence
 - make a device node on disk utilizing `mknod`, for gaining larger attack surface

Examples in container escape:
 - container starts with CAP_SYS_MODULE: inserting kernel module
 - container starting with CAP_SYS_ADMIN: `mknod` can make a device node on disk, providing debugfs a chance to overwrite host's filesystem, with ability from the dangerous CAP_SYS_ADMIN config:   mknod syscall

**Feature**

 - https://falco.org/docs/reference/rules/supported-events/
 - 👆 from the doc here, it seems that `mknod` and `init_module` has not been supported.
 - Apply for the support.

**Comment by Andreagit97** [comment]
ei @MagpieRYL thank you for that, I added these syscalls into our umbrella issue https://github.com/falcosecurity/falco/issues/1998!
You are right! these syscalls are not supported in Falco or at least they are supported in "generic" mode (i.e. you can see when these syscalls are called but not which are their parameters) 
Here you can find a more detailed report https://github.com/falcosecurity/libs/blob/master/driver/report.md
- the green ones are the "fully" supported
- the yellow ones are supported only in "generic" mode

Btw since these syscalls can have a relevant syscall impact maybe a generic implementation is not enough we will work on that ASAP :)

**Comment by incertum** [comment]
Since Falco 0.35.0 all generic syscalls are exposed to Falco, simply write a Falco rule, including `init_module`, and `finit_module` and `mknod` and many more. Please note Andrea's comment around them being generic hence we do not log specific args, but for Falco you can still access all of the `proc.*` fields from the process that issued these system calls.

**Comment by incertum** [comment]
@MagpieRYL would you be interested in contributing Falco rules https://github.com/falcosecurity/rules? We need more robust rules for container escapes in general.

**Comment by Andreagit97** [comment]
We should address this issue with:
* https://github.com/falcosecurity/libs/pull/1242
* https://github.com/falcosecurity/libs/pull/1270

(Thanks @therealbobo !)
