### ISSUE TITLE
[TRACKING] Breaking changes in Falco 0.39.0

### ISSUE THREAD

**Issue by Andreagit97** [falcosecurity/falco#3045]
This issue keeps track of all deprecated Falco features that will be removed in Falco 0.39.0

* remove options -D, -t, -T https://github.com/falcosecurity/falco/pull/3193

**Comment by FedeDP** [comment]
PR: https://github.com/falcosecurity/falco/pull/3311

**Comment by FedeDP** [comment]
Other breaking changes regard the newly introduced prometheus metrics in Falco 0.38.0:
* https://github.com/falcosecurity/falco/pull/3272
* https://github.com/falcosecurity/falco/pull/3319
* https://github.com/falcosecurity/falco/pull/3324

Thanks @incertum for the great job!
Since the feature was introduced in an `incubating` state, and it will remain so in the 0.39.0 release too, there was no guarantee of stability.
The feature should reach stable level in Falco 0.40.0.

**Comment by FedeDP** [comment]
Released! We can close this one!
/close
