### ISSUE TITLE
[BUILD] URL dependency to c-ares not valid

### ISSUE THREAD

**Issue by lecourtoisflo** [falcosecurity/falco#3248]
**Describe the bug**

Falco is not built if libcares is not installed on the system, as the URL

**How to reproduce it**

On an ubuntu with bpftool and its dependencies installed

**Expected behaviour**

Supposed to download c-ares if not found during build

**Screenshots**

**Environment**

- Falco version:
0.38.0
- System info:

- Cloud provider or hardware configuration:
- OS:
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
- Kernel:
5.15.0-112-generic x86_64 x86_64 x86_64 GNU/Linux
- Installation method:
Custom falco installation from github repo source

**Additional context**

Workaround: installing libcares works

**Comment by FedeDP** [comment]
Hi! Thanks for opening this issue! 
We already fixed the bug in libs: https://github.com/falcosecurity/libs/pull/1900; we just need to bump libs to master here on Falco.
Of course, Falco <= 0.38 won't build anymore using bundled c-ares because our cmake module used an old URL that is not available anymore (as you discovered).
/milestone 0.38.1
