### ISSUE TITLE
[Question] Difference about drop metrics

### ISSUE THREAD

**Issue by chenliu1993** [falcosecurity/falco#3348]
HI team, May i know is there a documentation about what is the purpose of below metrics from log?
falco.n_store_evts_drops
falco.n_retrieve_evts_drops( This keeps increasing)
falco.outputs_queue_num_drops
scap.n_drops_buffer_total
scap.n_drops_perc

Is there a documentation about these metrics? Thanks in advance

**Comment by FedeDP** [comment]
Hi! 
>  falco.n_store_evts_drops

this means that while storing an event for future retrieval (used in some cases in libs to retrieve syscall enter arguments, for example), we found that the thread associated with the event is no longer existing, thus we drop it instead of storing it: https://github.com/falcosecurity/libs/blob/master/userspace/libsinsp/parsers.cpp#L773

> falco.n_retrieve_evts_drops

We were not able to retrieve the stored event, for multiple reasons: https://github.com/falcosecurity/libs/blob/master/userspace/libsinsp/parsers.cpp#L827

>  falco.outputs_queue_num_drops

We dropped events from the output queue because the output queue itself was full: https://github.com/falcosecurity/falco/blob/master/userspace/falco/falco_outputs.cpp#L267
Strictly related to `outputs_queue.capacity` config option.

>  scap.n_drops_buffer_total

Number of events dropped between the driver and the userspace because the ring buffer was full: https://github.com/falcosecurity/libs/blob/master/driver/bpf/types.h#L269

>  scap.n_drops_perc

Percentage of drops against total number of events in the time between 2 different stats logs: https://github.com/falcosecurity/falco/blob/master/userspace/falco/stats_writer.cpp#L556

**Comment by chenliu1993** [comment]
Thanks! this much helps!
