### ISSUE TITLE
Use alpine base image for falco container

### ISSUE THREAD

**Issue by davidarcher** [falcosecurity/falco#384]
Is there a hard requirement for Falco to run on debian:unstable as the base image? Most other packages we're running use Alpine Linux as the baseline.

**Comment by mstemm** [comment]
The reason we use debian:unstable is that part of starting falco involves running dkms to build the kernel module on the fly. Since we run dkms from within the container, we also need several gcc versions available to match the requirements of the host system. And having multiple gcc versions available is best done using debian:unstable.

Separately, we found that alpine's use of musl instead of glibc caused several small dependency problems in various places. That testing was done in the context of the sysdig monitor/secure agent, which is more complex with more dependencies, so it might be feasible for falco. 

We are making some changes on the sysdig monitor/secure agent side to split the container in two, where one container is short-lived, responsible only for building/loading the kernel module and exiting. A second long-lived container relies on the kernel module being loaded. That second container could skip the dkms-related stuff which allows us to base it on a smaller image.

We could try the same approach here, although I'm not as confident we could use alpine as the basis of the long-lived container.

**Comment by mfdii** [comment]
@JPLachance Not sure if this can be done along with the idea of slimmer images (#532).

**Comment by JPLachance** [comment]
Hello @mfdii!

I think we should prioritize #532 instead of this for a couple of reasons:
1. Alpine is nice, but I'm not sure that it's a nice fit for an application like Falco.
2. Separating the kernel module build from the Falco container will allow us to use a complete build image for the build and a slim base image like the slim Ubuntu 18.04 image for the Falco container.
3. If we use eBPF, we don't need the Kernel module anymore, meaning can use a slim base image (of course, eBPF only works for recent versions of the Linux Kernel).

@davidarcher, what do you think?

**Comment by davidarcher** [comment]
@JPLachance, I concur with prioritizing #532 over this issue as my motivation in opening was in having a slimmer container, not necessarily Alpine.

**Comment by mfdii** [comment]
closing in favor of #532
