### ISSUE TITLE
Falco is dropping events.

### ISSUE THREAD

**Issue by srivastavaabhinav** [falcosecurity/falco#453]
Hi there,

I am trying to use Falco to collect "execve" system call and writing them into the log file. I have set the following values:

outputs:
  max_burst: 1000
  rate: 10

However, I can notice in the syslog messages that some "execve" calls are getting dropped. Can someone please provide some insights on why it is happening and what should be an ideal configuration to capture all "execve" system calls. In the future, I would like to extend this system by capturing few networking and file-system system calls as well.

Any help in this regard would be highly appreciated.

Thanks,
Abhinav

**Comment by mfdii** [comment]
Does the falco.yaml have `buffered_outputs: true`(https://github.com/falcosecurity/falco/blob/dev/falco.yaml#L63)? If there aren't enough events being generated you won't get them until the buffer is full. Set that to `false` and see if the events come through.

If not, please provide the OS, kernel version, Falco version, containerized or not, & deployment method.

**Comment by srivastavaabhinav** [comment]
Yes, buffered_outputs: true

We are getting events. But, we are seeing these lines in /var/log/messages:
rsyslogd-2177: imuxsock begins to drop messages from pid 7137 due to rate-limiting

We are not able to understand why some events are getting dropped and not getting stored in the log file. Do you think by setting "buffered_outputs: false", we will not see above lines in the /var/log/messages?

Appreciate your help!.

**Comment by mstemm** [comment]
I would first try to eliminate syslog as a potential source of drops by directly writing to a file. Once you've done that, you can (temporarily) enable debug logging. A message like this will be logged at debug level every time a notification is dropped due to token bucket throttling:

```
Skipping rate-limited notification for rule <rule>
```

If you find that the token bucket is dropping events, you'll probably want to increase the rate parameter of the token bucket. The default rate of 10 means that once the burst is exhausted, you are limited to 10 notifications per second. I'm not sure what your rate of execves is but that could be the problem.

Other things you can try is to only select the exit event (`evt.dir=<`) instead of both directions, which will halve the number of events. If you'd like to attach the rules you're using I can take a look.

Another thing to check is to make sure you're not dropping system calls. You can tell this by running falco with `falco -v` and then looking at the `Driver Events:` and `Driver Drops:` counts.
