### ISSUE TITLE
Cannot capture rename/unlink sys calls

### ISSUE THREAD

**Issue by srivastavaabhinav** [falcosecurity/falco#467]
Hi there,

I am trying to capture file rename and delete events. To this end, I am monitoring rename/renameat and unlink/unlinkat/rmdir events. However, I don't see these syscalls getting captured when I rename a file or delete it.

Any idea of this behavior? Help would be appreciated.

Thanks,
Abhinav

**Comment by mattpag** [comment]
hey @srivastavaabhinav,

I would suggest you to try using a broader filter (for example only filtering on the process name) and inspect the result so that we can find out which exact syscalls it's using to rename/delete files. Different OSs (or different version of the same OS) may have different behaviors (for example, using `open` or `openat`).

**Comment by mstemm** [comment]
Also, if you can create a sysdig capture that covers the activity you want to capture, but aren't able to capture with your rules, along with the rules you're using, we can take a look and see how we can change the rules to match the activity you want.
