### ISSUE TITLE
Falco &  AKS (Azure Kubernetes Service) or GKE with audit setup

### ISSUE THREAD

**Issue by prasenforu** [falcosecurity/falco#547]
Looking for documentation for setup Falco in AKS or GKE with Kubernetes Audit.

**Comment by mfdii** [comment]
Since you need access to the Master in order to change the audit backend you cannot currently use GKE. I'm not sure about AKS, but I couldn't find how to change the audit backend in any documentation. 

I do believe when GKE and AKS upgrade to kubernetes 1.13 you should be able to configure this through the AuditSinks resource.

**Comment by prasenforu** [comment]
But in kubernetes falco depends on audit of kubernetes. Not sure how I can use falco in cloud (AKS, GKE & EKS) kubernetes service.

**Comment by iverberk** [comment]
We just created a blog and tool to inspect the EKS audit logs with Falco: https://bit.ly/2U35vhu . Hope this helps.

**Comment by steven166** [comment]
I created also a tool for inspecting GKE audit logs with Falco: https://github.com/codeonline-io/falco-gke-audit-bridge.

**Comment by fntlnz** [comment]
That looks very cool @steven166  - wondering if we could integrate that directly into Falco once the gRPC input api is ready !

**Comment by dedman** [comment]
@prasenforu did you ever find out how to enable Kubernetes Audit in AKS?

**Comment by dedman** [comment]
Response from Azure "support"

> Right now we do not have specific documentation on how to use Falco, but for this case specifically, you would not be able to run the following command successfully:
`'--audit-policy-file=/etc/kubernetes/audit-policy.yaml --audit-webhook-config-file=/etc/kubernetes/audit-webhook-kubeconfig'`
on the api server, as this is completely managed by Azure

**Comment by prasenforu** [comment]
Only one option is available that is audit sink but I haven't tested.

**Comment by dedman** [comment]
I'm getting the following error
`error: unable to recognize "falco/falco-audit-sink.yaml": no matches for kind "AuditSink" in version "auditregistration.k8s.io/v1alpha1"`

So I'm it seems likely that Azure doesn't have the --audit-dynamic-configuration, etc configured for so that AuditSink works. Is AuditSink expected to work if you don't have access to modify the api-server config?

**Comment by mfdii** [comment]
I was able to do it - I can pair next week if needed 

—
Kris Nova 
Chief Open Source Advocate

**Comment by prakash1097** [comment]
So as of now alco's audit rules wont work for AKS- Azure kubernetes services?
