### ISSUE TITLE
Compatibility with AWS ECS Fargate

### ISSUE THREAD

**Issue by btorretta** [falcosecurity/falco#587]
Hello, it appears a requirement to run falco with the privileged flag in docker. Unfortunately fargate doesn't allow containers to run with this mode. Would it be possible to have perhaps a limited feature set, like potentially just looking for unanticipated processes run in the container via a sidecar container?

**Comment by fntlnz** [comment]
@btorretta Falco does not support running in a lightweight mode, however we have discussions around specifying a set of capabilities instead of asking for full privileges, see https://github.com/falcosecurity/falco/issues/628 .

We are also discussing the possibility to disable the kernel module features for those that can't use that  and just allow things like the audit log but for now there's no solution to this.

**Comment by fntlnz** [comment]
/triage unresolved

Triaging this as unresolved for now for the reasons in my previous comment.

**Comment by fntlnz** [comment]
Closing this since right now we can extract the ifnormation @btorretta is asking for using a kernel module or BPF probes and both require privileged capabilities.

However, a Fargate user might still be able to use falco only for k8s audit events after #730  is done.

Feel free to continue the discussion and reopen if needed.

**Comment by marcossv9** [comment]
Hi all,

I was wondering if there is a documentation or plans to release this early announced "kind of" compatibility to run Falco in AWS Fargate as mentioned in this [post](https://sysdig.com/blog/falco-support-on-aws-fargate/)

We are really excited about running falco as sidecar container in AWS Fargate.

Thanks in advance!
Marcos.

**Comment by kris-nova** [comment]
@marcossv9 please see the working group getting started next week that will be addressing this concretely https://lists.cncf.io/g/cncf-falco-dev/topic/userspace_producers_working/76589131

**Comment by kris-nova** [comment]
Also CC @btorretta :point_up:
