### ISSUE TITLE
Installing from source documentation

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/falco#595]
[The current documentation](https://falco.org/docs/source/) on how to install Falco from source lacks details like:

- Tools and their versions (e.g: lacking pkg-config leads to a broken build on the grpccpp plugin that is difficult to debug)
- Detailed description of the main cmake targets and explanation of the core components and pieces that are being built
- Compiler versions, this is quite obscure, it seems that for the kernel module we need a specific gcc version for compatibility with older kernels but we also install new toolchains and even clang in Dockerfiles
- Emphasis should be on the actual build tool, CMake, instead of on the builder docker image which certainly works but is not clear and understandable as a standard tool like CMake.

**Comment by leodido** [comment]
During today's work we also discussed other related topic (about dockerfiles etc.)

Thus I'm reporting them here for reference:

- Improve the existing docker envs (also their discoverability and documentation) in order to make easier for people to contribute to Falco

- Create other dev tools (eg., vagrant?) to facilitate the development of Falco

- Investigate the possibility to use [buildkit](https://github.com/moby/buildkit) for builders' artifacts

**Comment by leodido** [comment]
For future reference: https://github.com/falcosecurity/falco/blob/dev/docker/builder/Dockerfile#L24-L27 (duplicate libcurl-dev)

**Comment by leodido** [comment]
Closing because a first important step was made into https://github.com/falcosecurity/falco-website/pull/28.
