### ISSUE TITLE
Docs: architecture + performance, scalability, resource consumption bounds + failure modes + coding guidelines

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/falco#619]
I was digging into the documentation at falco.org and couldn't find a document with the architectural details of falco.
It would be useful for new contributors and users since both need to understand what falco is doing in order to contribute and use it.

**Comment by leodido** [comment]
We also need this in order to match the CNCF due diligence [technical](https://github.com/cncf/toc/blob/master/process/due-diligence-guidelines.md#technical) requirements.
One example is the [notary one](https://github.com/theupdateframework/notary/blob/master/docs/service_architecture.md).

**Comment by leodido** [comment]
I edited the title in order to use this issue as a reference also for other documents we need to write for the CNCF due diligence technical requirements.

Namely:
- [ ] document the performance, scalability, complexity, reliability, security trade-offs made, and whether they are tunable by the user or not
- [ ] document the failure modes
- [ ] document the coding guidelines

**Comment by fntlnz** [comment]
We still want this stalebot!
