### ISSUE TITLE
Falco probe loader build for older falco versions

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/falco#643]
After this, https://github.com/draios/sysdig/issues/1429 we noticed that Falco probe loader modules are built only for the latest Falco version, this creates problem to existing users upgrading to newer kernels.

This issue is an open discussion to decide what to do, I'm in favor of building the module for at least three versions.

What do you think? @leodido @mfdii @ldegio @mstemm  @Issif @prsimoes ?

**Comment by Issif** [comment]
Last three releases is a good number for me. 

Maybe we could provide an all-in-one factory for building kernel modules, a Dockerfile + Makefile, for example, to let anyone build modules for itself if missing (I think that Sysdig docker image may does this kind of behavior if module is missing)

We could also add a little stat mechanism (not blocking), when a falco can't start because of a missing kernel, it sends a stats with falco + kernel versions + arch to an endpoint. These metrics can help to determine which modules are the most called but missing.

My 2cts.

**Comment by mstemm** [comment]
I'd slightly lean towards 2 rather than 3 but I can live with either. I think a good time to make this change would be when we start hosting the artifacts separate from other sysdig oss artifacts.

**Comment by leodido** [comment]
I vote for 2.

L.
