### ISSUE TITLE
Precompiled kernels for DigitalOcean Kubernetes cluster

### ISSUE THREAD

**Issue by cnorthwood** [falcosecurity/falco#661]
**What would you like to be added**:

It would be great if the precompiled kernel modules included DigitalOcean's Kubernetes hosts.

**Why is this needed**:
To let Falco run on DO's managed Kubernetes infrastructure.

(Originally brought up on Slack, cc @fntlnz)

**Comment by michiels** [comment]
Hi @cnorthwood and @fntlnz 

Thanks for "joining up" and responding to the messages in Slack. It would indeed be great to have pre-compiled Sysdig Probe images on the DO K8s kernel versions!

As per @fntlnz suggestion on Slack I already tried to compile my own probe module and put that as a drop-into `~/.sysdig/` in a custom Docker container on Docker Hub for our company. However, that didn't work well because I built the module on a regular (non-K8s) Droplet and it seems the K8s droplets were running one kernel version behind the ones currently offered by Debian Stretch.

So hopefully the K8s cluster image on DO is updated soon that it's in sync again with Debian Stretch kernel headers from the Debian backports repository. That way a Probe kernel module can be built and offered by Sysdig as precompiled image, or I can add it to my own Docker image of falco.

**Comment by michiels** [comment]
Hi there! I have a follow up on this and running into some problems.

I just spun up regular Debian Stretch image on DigitalOcean and compiled the kernel module. I did this by pulling down the `falcosecurity/falco:latest` container image and manually running `make` in the `/usr/src/falco-xxx` directory. Then I copied the resulting `falco-probe.ko` to my workstation and put that in a Docker container image on Docker Hub under `/root/.sysdig/falco-probe-xxx`.

When I use my own Docker container image `firmhouse/falco:latest` in my Kubernetes cluster, I get an error at the point of loading the module:

```
insmod: ERROR: could not insert module /root/.sysdig/falco-probe-0.15.3-x86_64-4.19.0-0.bpo.5-amd64-cc14bb08bc0d4bfc47c4f589c06e1935.ko: Invalid module format
```

I am not sure if it helps, but `file falco-probe.ko` on my workstation gives me this:

```
$ file falco-probe.ko 
falco-probe.ko: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), BuildID[sha1]=cf2164399339248ea926effb8e87ae2b0c88adb6, with debug_info, not stripped
```

Any ideas what I might be doing wrong?

**Comment by mfdii** [comment]
Not exactly sure what you did wrong, but I tried to recreate and was able to build and insert the module, both on my build droplet and the k8s droplet. I built the module both with the falco container and manually on a Debian Stretch image. The steps are below. 

```
Launch debian 9.7 image.

Install stretch-backports:
vim /etc/apt/sources.list.d/stretch-backports.list
deb http://deb.debian.org/debian stretch-backports main

wget -q https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public
apt-key add DRAIOS-GPG-KEY.public

wget -q https://s3.amazonaws.com/download.draios.com/stable/deb/draios.list
mv draios.list /etc/apt/sources.list.d/draios.list

apt-get update

apt-get install falco

apt-get install -t stretch-backports linux-headers-4.19.0-0.bpo.5-amd64

dkms build -k 4.19.0-0.bpo.5-amd64 falco/0.15.3

md5=$(md5sum /usr/src/linux-headers-4.19.0-0.bpo.5-amd64/.config |cut -d' ' -f1)
mv /var/lib/dkms/falco/0.15.3/4.19.0-0.bpo.5-amd64/x86_64/module/falco-probe.ko ~/falco-probe-0.15.3-$(uname -m)-4.19.0-0.bpo.5-amd64-${md5}.ko

Stick the kernel module in a DO Space under a directory structure of:
/stable/sysdig-probe-binaries

Launch the Falco daemonset with an env variable like:
SYSDIG_PROBE_URL="https://myspacename.myregion.digitaloceanspaces.com"
```
The falco container will download the module from your Space and insert it. It you'd rather ship the module as a container, I'd suggest shipping your precompiled module as a container and having it launch as an init container that just `insmod`'s the module. 

In the meantime we are still going to research precompiling the module and making it publicly available. 

Also, it looks like you're going to get a bunch of informational Falco messages because `cilium` isn't on the allow list for some rules. We'd love a PR for that :)

**Comment by michiels** [comment]
@mfdii Many tanks for this. It worked. I have published my own binary to a DO Space and could succesfully launch the daemonset!

**Comment by michiels** [comment]
@mfdii By the way. No Cilium messages so far yet in my Falco logs. I'm using the default `yaml` files from this repo as standard configuration. What messages are you referring to so that I might contribute?

**Comment by fntlnz** [comment]
I think that @mfdii wanted to tell that since the DO k8s uses cilium for networking but the cilium binary is not trusted by falco so when using falco on DO what happens is that falco will complain about cilium doing privileged networking stuff.

See: https://github.com/falcosecurity/falco/blob/dev/rules/falco_rules.yaml#L162

**Comment by michiels** [comment]
@fntlnz Thank you for the explanation. Would it simply be a matter of adding cilium to that list? Or would that be an insecure practice?

**Comment by michiels** [comment]
@fntlnz @mfdii I'm fine with creating a PR for this! So I'll continue that. For now I'll assume that simply adding Cilium to the kubernetes tools whitelist is sufficient.
