### ISSUE TITLE
error while loading "raw_tracepoint/filler/sys_open_x" (no space left on device)

### ISSUE THREAD

**Issue by tahsinrahman** [falcosecurity/falco#775]
Hi, I'm new to ebpf and exploring the bpf parts of falco. I'm trying to load the bpf program using [iovisor/gobpf](https://github.com/iovisor/gobpf) library, but getting the following error. [full error](http://paste.ubuntu.com/p/xJ4WKn2WSz/)

```
panic: error while loading "raw_tracepoint/filler/sys_open_x" (no space left on device)
```

What device is it referring to? I've enough space left on my disk. 

Thanks!

**Comment by fntlnz** [comment]
Hi @tahsinrahman in order to get falco working you don't have to load the bpf program yourself, falco will load on its own when you enable BPF support.

So, to enable bpf support you need to use the `SYSDIG_BPF_PROBE` environment variable.

For example:
```
sudo SYSDIG_BPF_PROBE="" ./build/userspace/falco/falco --cri /var/run/docker/containerd/containerd.sock -c falco.yaml -r rules/falco_rules.yaml -r rules/k8s_audit_rules.yaml -r rules/falco_rules.local.yaml
```

When you do that you need the bpf program elf file in your home under the `.sysdig` folder, remember that the name of the file must be `falco-probe-bpf.o`.

```
~/.sysdig/falco-probe-bpf.o
```

Sorry if that's unclear!

Let me know if it works for you.

**Comment by tahsinrahman** [comment]
hi @fntlnz , thanks for your reply! The problem was my log buffer size was too small. i was able to load successfully after increasing buffer size.

**Comment by fntlnz** [comment]
Thanks,  you mean the kernel log buffer size right? Can you share how you fixed that? We might want to document it.

**Comment by tahsinrahman** [comment]
https://github.com/iovisor/gobpf/issues/103

i had to increase size [here](https://github.com/iovisor/gobpf/blob/master/elf/module.go#L172)

sysdig uses size [2^18](https://github.com/draios/sysdig/blob/master/userspace/libscap/scap_bpf.c#L61)(262144), gobpf defines size 524288, that is larger than defined in sysdig, but it was not enough :(

**Comment by fntlnz** [comment]
That really makes sense @tahsinrahman thanks a lot for bringing it as a reference!
I'm closing this as you solved!
